#  Assignment For Numpy


Difficulty Level **Beginner**

Import the numpy package under the name np

In [22]:
import numpy as np

Create a null vector of size 10

In [26]:
vector=np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a vector with values ranging from 10 to 49

In [29]:
ranging_vector=np.arange(10,49)
ranging_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

Find the shape of previous array in question 3

In [30]:
ranging_vector.shape

(39,)

Print the type of the previous array in question 3

In [31]:
ranging_vector.dtype

dtype('int32')

Print the numpy version and the configuration

In [33]:
print(np.__version__,np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
1.19.2 None


Print the dimension of the array in question 3

In [34]:
ranging_vector.ndim

1

Create a boolean array with all the True values

In [35]:
vector_bool=np.array(range(1,6),dtype="bool")
vector_bool

array([ True,  True,  True,  True,  True])

Create a two dimensional array

In [43]:
array2D=np.ones((2,2))
array2D

array([[1., 1.],
       [1., 1.]])

Create a three dimensional array

In [45]:
array3D=np.zeros((3,3))
array3D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Difficulty Level **Easy**

Reverse a vector (first element becomes last)

Create a null vector of size 10 but the fifth value which is 1

In [49]:
vectorNull=np.zeros(10)
vectorNull[5]=1
vectorNull

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Create a 3x3 identity matrix

In [50]:
matrix=np.identity(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

arr = np.array([1, 2, 3, 4, 5])
Convert the data type of the given array from int to float

In [56]:
arr = np.array([1, 2, 3, 4, 5],dtype="float32") 
arr

array([1., 2., 3., 4., 5.], dtype=float32)

arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

Multiply arr1 with arr2

In [58]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

Make an array by comparing both the arrays provided abo

In [59]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print("a>b")
print(np.greater(arr1,arr2))

a>b
[[ True False  True]
 [False  True False]]


Extract all odd numbers from arr with values(0-9)

In [72]:
arr=np.arange(9)
oddArr=filter(lambda val: val%2==0,arr)
list(oddArr)

[0, 2, 4, 6, 8]

Replace all odd numbers to -1 from previous array

In [74]:
arr[arr%2==0]=-1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1])

arr = np.arange(10)

Replace the values of indexes 5,6,7 and 8 to 12

In [75]:
arr = np.arange(10)
arr[5]=arr[6]=arr[7]=arr[8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

Create a 2d array with 1 on the border and 0 inside

In [76]:
arr = np.ones((8, 8))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])


Difficulty Level **Medium**

arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

Replace the value 5 to 12

In [77]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Convert all the values of 1st array to 64

In [79]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[0][:] = 64
arr3d[1][:] = 64

arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[64, 64, 64],
        [64, 64, 64]]])

Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [85]:
arr=np.arange(9).reshape(3,3)
arr[0]

array([0, 1, 2])

Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [88]:
arr=np.arange(9).reshape(3,3)
arr[1][1]

4

Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [91]:
arr=np.arange(9).reshape(3,3)
arr[0:-1,-1]

array([2, 5])

Create a 10x10 array with random values and find the minimum and maximum values

In [113]:
arr = np.arange(100).reshape(10, 10)
maxInColumns = np.amax(arr, axis=1)


# 27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])¶

In [114]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Find the positions where elements of a and b match

In [115]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

Find all the values from array **data** where the values from array **names** are not equal to **Will**

In [116]:

import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
# data = np.random.randn(7,4) # --> This gives floating point numbers
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where(name[data] != "Will"))

[0 3]
(array([0, 1], dtype=int64),)


names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

Find all the values from array **data** where the values from array names are not equal to **Will** and **Joe**

In [118]:

import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
# data = np.random.randn(7,4) # --> This gives floating point numbers
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where((name[data] != "Joe") & (name[data] != "Will")))

[2 5 5 2 6 4 4 6]
(array([], dtype=int64),)


Difficulty Level **Hard**

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [119]:
arr=np.random.uniform(low=1.0,high=15.0,size=(5,3))
arr

array([[14.11409557, 12.59671891,  3.37827199],
       [ 3.48801287,  6.68874861,  5.01084312],
       [ 2.01943519,  5.85274909,  8.62630846],
       [ 4.75233842,  1.76127345,  5.86904062],
       [ 6.80811916, 14.74556017, 13.96414973]])

Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [122]:
arrk = np.random.uniform(low=1.0, high=16.0, size=(2,2,4))
arrk

array([[[ 7.27069021, 14.67592614,  5.8274613 ,  1.62852258],
        [12.85006285, 14.17856855,  8.44419028, 13.90749347]],

       [[ 3.26357588, 14.82851576,  9.27055545,  2.32583838],
        [12.81647981, 13.02307509, 15.56956844,  2.30870397]]])

Swap axes of the array you created in Question 32

In [123]:
np.swapaxes(arrk,0,1)

array([[[ 7.27069021, 14.67592614,  5.8274613 ,  1.62852258],
        [ 3.26357588, 14.82851576,  9.27055545,  2.32583838]],

       [[12.85006285, 14.17856855,  8.44419028, 13.90749347],
        [12.81647981, 13.02307509, 15.56956844,  2.30870397]]])

Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [124]:

import math

arr = np.arange(10)
print(arr)
new_arr = filter(lambda x: x if math.sqrt(x) > 0.5 else 0, arr)
np.asarray(list(new_arr))

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays


In [125]:
arr1 = np.random.randint(12, size=random.randrange(0, 12))
arr2 = np.random.randint(12, size=random.randrange(0, 12))
print(arr1)
print(arr2)
np.where(arr1 == arr2)

[ 8 11  2 11  7  6  0  4]
[4 0 2 4 0 9 9 5]


(array([2], dtype=int64),)

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

Find the unique names and sort them out!

In [126]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names) 

array(['Bob', 'Joe', 'Will'], dtype='<U4')

a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])


From array a remove all items present in array b



In [127]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
val = np.intersect1d(a, b)

a = filter(lambda x: x if x not in val else None, a)
np.asarray(list(a))


array([1, 2, 3, 4])

Following is the input NumPy array delete column two and insert following new column in its place.


sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])



newColumn = numpy.array([[10,10,10]])



In [129]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray[:, 1] = 10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
